Collision= Class.extend({

	collider:null,			//The Collider we hit (Read Only).
	contacts:null,			//The contact points generated by the physics engine.
	gameObject:null,		//The GameObject whose collider we are colliding with. (Read Only).
	relativeVelocity:null,	//The relative linear velocity of the two colliding objects (Read Only).
	rigidbody:null,			//The Rigidbody we hit (Read Only). This is null if the object we hit is a collider with no rigidbody attached.
	transform:null,			//The Transform of the object we hit (Read Only).

	init:function(obj){
		for (var prop in obj ){
			if (this.hasOwnProperty(prop)){
				this[prop] = obj[prop];
			}
		}
	}
});